/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGithubWebhookProjectIdRouteImport } from './routes/api/public/github-webhook.$projectId'

const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubWebhookProjectIdRoute =
  ApiPublicGithubWebhookProjectIdRouteImport.update({
    id: '/api/public/github-webhook/$projectId',
    path: '/api/public/github-webhook/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/onboarding': typeof OnboardingRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
  '/twin': typeof TwinRoute
  '/api/public/github-webhook/$projectId': typeof ApiPublicGithubWebhookProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/onboarding': typeof OnboardingRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
  '/twin': typeof TwinRoute
  '/api/public/github-webhook/$projectId': typeof ApiPublicGithubWebhookProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/onboarding': typeof OnboardingRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
  '/twin': typeof TwinRoute
  '/api/public/github-webhook/$projectId': typeof ApiPublicGithubWebhookProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/auth'
    | '/copilot'
    | '/onboarding'
    | '/roadmap'
    | '/settings'
    | '/simulator'
    | '/team'
    | '/twin'
    | '/api/public/github-webhook/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/auth'
    | '/copilot'
    | '/onboarding'
    | '/roadmap'
    | '/settings'
    | '/simulator'
    | '/team'
    | '/twin'
    | '/api/public/github-webhook/$projectId'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/auth'
    | '/copilot'
    | '/onboarding'
    | '/roadmap'
    | '/settings'
    | '/simulator'
    | '/team'
    | '/twin'
    | '/api/public/github-webhook/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AuthRoute: typeof AuthRoute
  CopilotRoute: typeof CopilotRoute
  OnboardingRoute: typeof OnboardingRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  TeamRoute: typeof TeamRoute
  TwinRoute: typeof TwinRoute
  ApiPublicGithubWebhookProjectIdRoute: typeof ApiPublicGithubWebhookProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github-webhook/$projectId': {
      id: '/api/public/github-webhook/$projectId'
      path: '/api/public/github-webhook/$projectId'
      fullPath: '/api/public/github-webhook/$projectId'
      preLoaderRoute: typeof ApiPublicGithubWebhookProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AuthRoute: AuthRoute,
  CopilotRoute: CopilotRoute,
  OnboardingRoute: OnboardingRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  TeamRoute: TeamRoute,
  TwinRoute: TwinRoute,
  ApiPublicGithubWebhookProjectIdRoute: ApiPublicGithubWebhookProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
